name: Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: marcbran/jsonnet-kit
      - name: Run Jsonnet tests
        run: jsonnet-kit test .
